In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.shape

(16000, 2)

In [6]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [7]:
unique_emotions=df['emotion'].unique()
emotion_num={}
i=0
for emo in unique_emotions:
    emotion_num[emo]=i
    i+=1

df['emotion']=df['emotion'].map(emotion_num)

In [8]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

## Text Cleaning

### convert to lower case

In [9]:
df['text']=df['text'].str.lower()

### remove punctutations

In [10]:
import string
def remove_punctuatn(text):
    return text.translate(str.maketrans('','',string.punctuation))

In [11]:
df['text']=df['text'].apply(remove_punctuatn)

### remove numbers

In [12]:
def remove_numbers(text):
    new=''
    for i in text:
        if not i.isdigit():
            new+=i
    return new

In [13]:
df['text']=df['text'].apply(remove_numbers)

### remove emojis and special characters

In [14]:
def remove_emoji(text):
    new=''
    for i in text:
        if i.isascii():
            new+=i
    return new

In [15]:
df['text']=df['text'].apply(remove_emoji)

### remove stopwords

stopwords add noise [Machine learning] so let's remove stop words

In [16]:
import nltk

In [17]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [25]:
print(nltk.__version__)

3.9.4

In [18]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Raj\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Raj\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [26]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Raj\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [27]:
stop_words=set(stopwords.words('english'))
#stop_words

In [28]:
def remoce_txt(text):
    words=word_tokenize(text)
    cleaned_text=[]
    for i in words:
        if i not in stop_words:
            cleaned_text.append(i)
    return ' '.join(cleaned_text)

In [29]:
df['text']=df['text'].apply(remoce_txt)

In [30]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1